import React, { createContext, useState, useContext, useEffect, useCallback } from 'react';
import { db } from '../db';

const translations = {
  ar: {
    loadingData: "جاري تحميل البيانات",
    pleaseWait: "الرجاء الانتظار قليلاً",
    customerNotFound: "لم يتم العثور على العميل",
    supplierNotFound: "لم يتم العثور على المورد",
    sidebarWelcome: "مرحباً, {0}",
    sidebarLogout: "تسجيل الخروج",
    navDashboard: "لوحة التحكم",
    navPOS: "نقطة البيع",
    navInventory: "المخزون",
    navCategories: "التصنيفات",
    navSales: "المبيعات",
    navPurchases: "المشتريات",
    navSupplierReturns: "مرتجعات الموردين",
    navCustomers: "العملاء",
    navSuppliers: "الموردين",
    navAdjustments: "تسويات المخزون",
    navReports: "التقارير",
    navSessions: "إدارة الجلسات",
    navSettings: "الإعدادات",
    // Settings Page
    settingsTitle: 'الإعدادات',
    languageSettings: 'إعدادات اللغة',
    appLanguage: 'لغة التطبيق',
    languageArabic: 'العربية',
    languageEnglish: 'English',
    currencySettings: 'إعدادات العملة',
    appCurrency: 'عملة التطبيق',
    saveCurrency: 'حفظ العملة',
    currencyEGP: 'جنيه مصري (EGP)',
    currencyUSD: 'دولار أمريكي (USD)',
    currencyEUR: 'يورو (EUR)',
    currencySAR: 'ريال سعودي (SAR)',
    generalSettings: 'إعدادات عامة',
    taxRate: 'معدل الضريبة',
    showTaxInReceipt: 'إظهار الضريبة في الفاتورة',
    saveTaxRate: 'حفظ معدل الضريبة',
    savedSuccessfully: 'تم الحفظ بنجاح!',
    storeInfo: 'معلومات المتجر (للفاتورة)',
    storeName: 'اسم المتجر',
    storeAddress: 'العنوان',
    storePhone: 'الهاتف',
    storeLogo: 'شعار المتجر (Logo)',
    browseFiles: 'استعراض الملفات',
    saveStoreInfo: 'حفظ معلومات المتجر',
    userManagement: 'إدارة المستخدمين',
    addUser: 'إضافة مستخدم',
    username: 'اسم المستخدم',
    role: 'الصلاحية',
    actions: 'إجراءات',
    roleAdmin: 'مدير',
    roleCashier: 'كاشير',
    edit: 'تعديل',
    delete: 'حذف',
    confirmDelete: "تأكيد الحذف",
    deleteUserConfirmation: 'هل أنت متأكد من حذف المستخدم "{0}"؟ هذا الإجراء لا يمكن التراجع عنه.',
    cancel: "إلغاء",
    confirm: "تأكيد",
    editUser: "تعديل المستخدم",
    addNewUser: "إضافة مستخدم جديد",
    usernameRequired: "اسم المستخدم مطلوب.",
    passwordRequired: "كلمة المرور مطلوبة للمستخدم الجديد.",
    password: "كلمة المرور",
    usernameCannotBeChanged: "لا يمكن تغيير اسم المستخدم.",
    leaveBlankToKeep: "اتركه فارغاً لعدم التغيير",
    save: "حفظ",
    networkSyncSettings: "مزامنة الشبكة",
    networkSyncDescription: "لتمكين المزامنة الفورية بين الأجهزة، قم بتشغيل خادم المزامنة على جهاز رئيسي وأدخل عنوانه هنا على جميع الأجهزة الأخرى.",
    serverUrlLabel: "عنوان خادم المزامنة",
    serverUrlPlaceholder: "مثال: ws://192.168.1.5:8080",
    connectionStatusLabel: "حالة الاتصال",
    statusConnected: "متصل",
    statusConnecting: "جاري الاتصال...",
    statusDisconnected: "غير متصل",
    saveServerUrlButton: "حفظ وتوصيل",
    dataManagement: "إدارة البيانات",
    dataManagementDescription: "تصدير جميع بياناتك في ملف واحد للاحتفاظ بنسخة احتياطية، أو استيراد ملف نسخة احتياطية لاستعادة البيانات. تحذير: الاستيراد سيحذف جميع البيانات الحالية.",
    exportData: "تصدير البيانات",
    importData: "استيراد البيانات",
    importConfirmMessage: "تحذير! سيؤدي استيراد البيانات إلى حذف جميع البيانات الحالية بشكل نهائي واستبدالها بالبيانات الموجودة في ملف النسخة الاحتياطية. هل أنت متأكد من المتابعة؟",
    restoreConfirmMessage: "هل أنت متأكد من أنك تريد استعادة النسخة الاحتياطية من {0}؟ سيتم حذف جميع البيانات الحالية.",
    autoBackupTitle: "النسخ الاحتياطي اليومي التلقائي",
    autoBackupTimeSetting: "توقيت النسخ الاحتياطي التلقائي",
    autoBackupTimeDescription: "اختر الوقت الذي سيتم فيه إنشاء النسخة الاحتياطية اليومية. سيتم تشغيلها عند فتح البرنامج بعد هذا الوقت.",
    saveBackupTime: "حفظ التوقيت",
    autoBackupDescription: "يقوم النظام تلقائيًا بإنشاء نسخة احتياطية يوميًا ويحتفظ بآخر 7 نسخ. يمكنك استعادة أي منها أو تنزيلها.",
    noAutoBackups: "لا توجد نسخ احتياطية تلقائية متاحة.",
    backupDate: "نسخة يوم: {0}",
    restore: "استعادة",
    download: "تنزيل",
    confirmActionTitle: "تأكيد الإجراء",
    importSuccess: "تم استيراد البيانات بنجاح! سيتم إعادة تحميل التطبيق.",
    importFailed: "فشل الاستيراد: {0}",
    exportFailed: "فشل التصدير: {0}",
    backupNotFound: "لم يتم العثور على النسخة الاحتياطية.",
    settingsAutoFileBackup: "النسخ الاحتياطي التلقائي للملفات",
    settingsAutoFileBackupDesc: "اختر مجلدًا على جهاز الكمبيوتر الخاص بك لحفظ النسخ الاحتياطية اليومية تلقائيًا. سيطلب المتصفح الإذن مرة واحدة.",
    settingsChooseFolder: "اختر مجلد",
    settingsSelectedFolder: "المجلد المختار",
    settingsClearSelection: "مسح الاختيار",
    settingsFolderSetSuccess: "تم تعيين مجلد النسخ الاحتياطي بنجاح!",
    settingsFolderCleared: "تم مسح اختيار مجلد النسخ الاحتياطي.",
    settingsFileSystemNotSupported: "الميزة غير مدعومة",
    settingsFileSystemNotSupportedDesc: "هذه الميزة متاحة فقط في المتصفحات الحديثة على أجهزة الكمبيوتر المكتبية مثل Chrome و Edge.",
    settingsFileSystemInsecure: "مطلوب سياق آمن (Secure Context)",
    settingsFileSystemInsecureDesc: "لأسباب أمنية، تعمل هذه الميزة فقط عند الوصول للتطبيق عبر `localhost` أو اتصال `https`. الوصول عبر عنوان IP للشبكة المحلية (مثل http://192.168.x.x) غير مدعوم.",
    autoBackupSavedToFile: "تم حفظ النسخة الاحتياطية التلقائية أيضًا في المجلد الذي اخترته.",
    autoBackupFileSaveError: "تعذر حفظ النسخة الاحتياطية في المجلد المختار. يرجى التحقق من الأذونات.",
    // Login Page
    loginWelcome: "مرحباً بعودتك! الرجاء تسجيل الدخول.",
    loginButton: "تسجيل الدخول",
    loginError: "اسم المستخدم أو كلمة المرور غير صحيحة.",
    // Dashboard
    dashboardTitle: "لوحة التحكم الرئيسية",
    totalSales: "إجمالي المبيعات",
    totalTransactions: "عدد المعاملات",
    totalProducts: "عدد المنتجات",
    lowStockProducts: "منتجات قاربت على النفاد",
    weeklySales: "مبيعات الأسبوع الحالي",
    noSalesThisWeek: "لا توجد مبيعات مسجلة هذا الأسبوع.",
    slowMovingProducts: "المنتجات الراكدة (لم تبع آخر 30 يوم)",
    stockLabel: "المخزون",
    noSlowMovingProducts: "لا توجد منتجات راكدة حالياً.",
    latestSales: "أحدث المبيعات",
    invoiceNumber: "رقم الفاتورة",
    date: "التاريخ",
    paymentMethod: "طريقة الدفع",
    total: "الإجمالي",
    dismissAlert: "إخفاء التنبيه",
    // Payment Methods
    paymentMethodCash: 'نقدي',
    paymentMethodCard: 'بطاقة',
    paymentMethodDeferred: 'آجل',
    paymentMethodMultiple: 'متعدد',
    paymentMethodUnspecified: 'غير محدد',
    // Notifications
    notifLowStock: 'المنتج "{0}" على وشك النفاد. الكمية المتبقية: {1}',
    notifExpiry: 'توجد كميات من المنتج "{0}" تقترب من انتهاء الصلاحية.',
    // POS Page
    scanBarcodePlaceholder: "امسح أو أدخل الباركود هنا...",
    searchProductsPlaceholder: "ابحث عن المنتجات...",
    categories: "التصنيفات",
    allCategories: "الكل",
    home: "الرئيسية",
    noItemsToDisplay: "لا توجد عناصر لعرضها.",
    posBill: "الفاتورة",
    parkedSalesTitle: "الفواتير المعلقة",
    posEmptyCart: "السلة فارغة",
    subtotal: "المجموع الفرعي",
    discount: "الخصم",
    tax: "الضريبة",
    customer: "العميل",
    customerNamePlaceholder: "اكتب اسم العميل...",
    newCustomerWillBeCreated: "سيتم إنشاء عميل جديد بهذا الاسم.",
    pay: "دفع",
    deferredSale: "بيع آجل",
    parkSale: "تعليق الفاتورة",
    sessionClosedTitle: "الجلسة مغلقة",
    sessionClosedBody: "يجب عليك بدء جلسة عمل جديدة من صفحة إدارة الجلسات لتتمكن من تسجيل المبيعات.",
    cashCustomer: "زبون نقدي",
    productNotFound: "المنتج غير موجود",
    productNotFoundInStock: "المنتج '{0}' غير موجود في المخزون.",
    insufficientStockError: "فشل إتمام البيع للمنتج \"{0}\": الكمية المطلوبة ({1}) أكبر من الكمية المتاحة ({2}).",
    deferredSaleCashCustomerError: 'لا يمكن البيع الآجل لـ "زبون نقدي". الرجاء إدخال اسم عميل.',
    deferredSaleNoCreateError: "لا يمكن إتمام البيع الآجل بدون تسجيل العميل.",
    saleCompletionError: "حدث خطأ أثناء إتمام البيع. الرجاء المحاولة مرة أخرى.",
    saleFailedWithReason: "فشل إتمام البيع: {0}",
    // POS Modals
    weightEntryTitle: "إدخال الوزن لـ: {0}",
    pricePerUnit: "السعر لكل {0}: {1}",
    weightPlaceholder: "الوزن بـ ({0})",
    calculatedPrice: "السعر المحسوب",
    add: "إضافة",
    unregisteredCustomerTitle: "عميل غير مسجل",
    unregisteredCustomerBody: 'العميل "{0}" غير موجود. هل ترغب في إضافته إلى قائمة العملاء؟',
    unregisteredCustomerDeferredNote: "ملاحظة: لا يمكن إتمام البيع الآجل بدون تسجيل العميل.",
    cancelSale: "إلغاء البيع",
    continueSaleOnly: "لا، متابعة البيع فقط",
    addAndContinue: "نعم، إضافة ومتابعة",
    selectUnitFor: "اختر وحدة لـ: {0}",
    parkedSaleOnDate: "فاتورة بتاريخ: {0}",
    parkedSaleDetails: "عدد الأصناف: {0}, الإجمالي: {1}",
    retrieve: "استرجاع",
    noParkedSales: "لا توجد فواتير معلقة.",
    parkedSaleNote: 'فاتورة لـ {0}',
    // Payment Modal
    cashPaymentTitle: "الدفع النقدي",
    totalAmountDue: "المبلغ الإجمالي المطلوب",
    amountReceivedFromCustomer: "المبلغ المستلم من العميل",
    exactAmount: "المبلغ بالضبط",
    changeDueToCustomer: "الباقي للعميل",
    completeSale: "إتمام البيع",
    // hooks/usePosState.ts
    categoryInUseError: "لا يمكن حذف التصنيف لأنه مستخدم في بعض المنتجات.",
    saleUpdatedSuccess: "تم تحديث الفاتورة بنجاح.",
    addPurchaseError: "فشل في إضافة فاتورة الشراء.",
    purchaseNotFound: "فاتورة الشراء غير موجودة.",
    deletePurchaseError: "فشل في حذف فاتورة الشراء.",
    addSupplierReturnError: "فشل في إضافة مرتجع المورد.",
    supplierReturnNotFound: "مرتجع المورد غير موجود.",
    deleteSupplierReturnError: "فشل في حذف مرتجع المورد.",
    cannotDeleteCurrentUser: "لا يمكنك حذف المستخدم الحالي.",
    noCurrentUser: "لا يوجد مستخدم حالي.",
    sessionAlreadyActive: "توجد جلسة عمل نشطة بالفعل.",
    mustStartSessionFirst: "يجب بدء جلسة عمل أولاً لتسجيل المصروفات.",
    noActiveSessionToEnd: "لا توجد جلسة نشطة لإنهاءها.",
    // pages/Sales.tsx
    itemCount: "عدد الأصناف",
    cost: "التكلفة",
    profit: "الربح",
    salesLogTitle: "سجل المبيعات",
    searchByInvoiceNumber: "ابحث برقم الفاتورة...",
    searchByCustomerName: "ابحث باسم العميل...",
    exporting: "جاري التصدير...",
    exportSelectedToWord: "تصدير المحدد إلى Word",
    exportToExcel: "تصدير إلى Excel",
    selectAll: "تحديد الكل",
    selectInvoice: "تحديد الفاتورة {0}",
    returnEdit: "إرجاع / تعديل",
    exportAsImage: "تصدير كصورة",
    print: "طباعة",
    // components/Receipt.tsx
    allowPopupsForPrinting: "يرجى السماح بالنوافذ المنبثقة للطباعة.",
    storeLogoAlt: "شعار المتجر",
    phoneLabel: "الهاتف",
    item: "الصنف",
    quantity: "الكمية",
    price: "السعر",
    paidWith: "مدفوع بـ {0}",
    newBalance: "الرصيد الجديد",
    thankYouMessage: "شكراً لزيارتكم!",
    close: "إغلاق",
    // New Translations
    inventoryTitle: "إدارة المخزون",
    inventorySearchPlaceholder: "ابحث بالاسم أو SKU...",
    inventoryFilterAllCategories: "كل التصنيفات",
    inventoryFilterAllStock: "كل حالات المخزون",
    inventoryFilterInStock: "متوفر",
    inventoryFilterLowStock: "مخزون منخفض",
    inventoryFilterOutOfStock: "نفد المخزون",
    inventoryAddNewProduct: "إضافة منتج جديد",
    inventoryTableProduct: "المنتج",
    inventoryTableSku: "SKU",
    inventoryTableCategory: "الفئة",
    inventoryTablePrice: "السعر (أكبر وحدة)",
    inventoryTablePriceUnit: "وحدة السعر",
    inventoryTableStock: "المخزون",
    inventoryTableStockUnit: "وحدة المخزون",
    inventoryPrintBarcode: "طباعة باركود",
    inventoryDeleteConfirmMessage: "هل أنت متأكد من رغبتك في حذف هذا العنصر؟",
    inventoryStatusExpiresSoon: "صلاحية قريبة",
    inventoryStatusLowStock: "مخزون منخفض",
    inventoryStatusOutOfStock: "نفد المخزون",
    barcodeLabelTitle: "ملصق الباركود",
    productModalEditTitle: "تعديل المنتج",
    productModalAddTitle: "إضافة منتج جديد",
    productModalProductName: "اسم المنتج",
    productModalProductNamePlaceholder: "مثال: قهوة اسبريسو",
    productModalSku: "SKU (الباركود)",
    productModalSkuPlaceholder: "امسح الباركود أو أدخله يدويًا",
    productModalCategory: "التصنيف",
    productModalCategorySelect: "-- اختر تصنيفًا --",
    productModalSellingMethod: "طريقة البيع",
    productModalSellingMethodUnit: "بالوحدة (قطعة، علبة..)",
    productModalSellingMethodWeight: "بالوزن (كيلو، جرام..)",
    productModalUnitsAndPrices: "وحدات القياس والأسعار",
    productModalUnitHelpTextUnit: "ابدأ بإدخال الوحدة الأكبر للمنتج (مثل كرتونة). ثم أضف الوحدات الأصغر بداخلها.",
    productModalUnitHelpTextWeight: "أدخل الوحدة الأساسية للوزن (مثل كيلوجرام) وسعر البيع والتكلفة لهذه الوحدة.",
    productModalBaseUnitLargest: "الوحدة الأساسية (الأكبر)",
    productModalBaseUnitWeight: "الوحدة الأساسية للوزن",
    productModalOfNextUnit: "من الوحدة التالية",
    productModalUnitNameLabel: "اسم الوحدة",
    productModalUnitNamePlaceholderUnit: "كرتونة، علبة..",
    productModalUnitNamePlaceholderWeight: "كيلوجرام، جرام..",
    productModalSellingPrice: "سعر بيع ({0})",
    productModalCostPrice: "سعر تكلفة ({0})",
    productModalUnit: "الوحدة",
    productModalAddSmallerUnit: "+ إضافة وحدة أصغر",
    productModalInitialStock: "الكمية المبدئية بالمخزون",
    productModalCannotEditStock: "لا يمكن تعديل المخزون من هنا. استخدم المشتريات أو التسويات.",
    productModalStockHelpText: "سيتم تخزين الكمية في المخزن بأصغر وحدة قياس تم تعريفها.",
    productModalExpiryDate: "تاريخ انتهاء الصلاحية",
    productModalImage: "صورة المنتج (اختياري)",
    productModalNoImage: "لا توجد صورة",
    productModalDescription: "وصف المنتج",
    productModalDescriptionPlaceholder: "وصف قصير وجذاب للمنتج...",
    productModalCompleteUnitInfo: "يجب إكمال بيانات جميع وحدات القياس.",
    productModalStockUnitError: "حدث خطأ في تحديد وحدة المخزون.",
    categoriesTitle: "إدارة التصنيفات",
    categorySearchPlaceholder: "ابحث عن تصنيف...",
    categoryAddMain: "إضافة تصنيف رئيسي",
    categorySearchResults: "نتائج البحث عن \"{0}\"",
    categoryTreeTitle: "شجرة التصنيفات",
    categoryNoResults: "لا توجد تصنيفات تطابق بحثك.",
    categoryProductCount: "المنتجات: {0}",
    categoryAddSub: "إضافة فرعي",
    categoryDeleteConfirm: "هل أنت متأكد من رغبتك في حذف هذا التصنيف وجميع تصنيفاته الفرعية؟",
    categoryModalEditTitle: "تعديل التصنيف",
    categoryModalAddSubTitle: "إضافة تصنيف فرعي لـ {0}",
    categoryModalAddMainTitle: "إضافة تصنيف رئيسي",
    categoryModalNamePlaceholder: "اسم التصنيف",
    categoryModalImageLabel: "صورة التصنيف (اختياري)",
    categoryModalImagePlaceholder: "صورة",
    categoryModalImagePreviewAlt: "معاينة",
    categoryModalChangeImage: "تغيير الصورة",
    categoryModalParentOptionMain: "-- تصنيف رئيسي --",
    purchasesTitle: "إدارة المشتريات",
    purchasesAddButton: "إضافة فاتورة شراء",
    purchasesTableInvoice: "رقم الفاتورة",
    purchasesTableSupplier: "المورد",
    purchasesTablePaid: "المدفوع",
    purchasesTableView: "عرض",
    purchasesDeleteConfirm: "هل أنت متأكد من حذف هذه الفاتورة؟ سيتم عكس التغييرات في المخزون ورصيد المورد.",
    purchaseDetailsTitle: "تفاصيل فاتورة الشراء",
    purchaseDetailsRemaining: "المتبقي",
    notes: "ملاحظات",
    notesOptional: "ملاحظات (اختياري)",
    purchaseModalTitle: "إضافة فاتورة شراء جديدة",
    purchaseModalSelectSupplier: "-- اختر المورد --",
    purchaseModalReference: "الرقم المرجعي",
    purchaseModalReferenceOptional: "الرقم المرجعي (اختياري)",
    purchaseModalItems: "الأصناف",
    purchaseModalSearchProduct: "ابحث عن منتج...",
    purchaseModalSelectUnit: "-- اختر وحدة --",
    purchaseModalExpiresOn: "تنتهي في: {0}",
    purchaseModalValidationError: "يرجى التأكد من اختيار منتج ووحدة وإدخال كمية وسعر تكلفة صالحين.",
    purchaseModalNoItems: "لم يتم إضافة أصناف بعد",
    purchaseModalAmountPaid: "المبلغ المدفوع",
    purchaseModalNotesPlaceholder: "أي تفاصيل إضافية...",
    purchaseModalSaveButton: "حفظ فاتورة الشراء",
    purchaseModalSupplierItemError: "يرجى اختيار مورد وإضافة منتج واحد على الأقل.",
    purchaseModalInvalidAmountError: "المبلغ المدفوع غير صالح.",
    returnsTitle: "مرتجعات الموردين",
    returnsAddButton: "إضافة مرتجع جديد",
    returnsTableReturnNo: "رقم المرتجع",
    returnsDeleteConfirm: "هل أنت متأكد؟ سيتم عكس التغييرات في المخزون ورصيد المورد.",
    returnDetailsTitle: "تفاصيل مرتجع المورد",
    returnDetailsTotal: "إجمالي المرتجع",
    returnModalTitle: "إضافة مرتجع مورد جديد",
    returnModalReturnedItems: "الأصناف المرتجعة",
    purchaseModalSelectUnitFirst: "اختر منتج",
    returnModalTotal: "إجمالي المرتجع",
    returnModalSaveButton: "حفظ المرتجع",
    customersTitle: "إدارة العملاء",
    customersSearchPlaceholder: "ابحث بالاسم أو الهاتف...",
    customersAddButton: "إضافة عميل",
    customersTableName: "الاسم",
    customersTablePhone: "الهاتف",
    customersTableBalance: "الرصيد",
    customersAddPayment: "إضافة دفعة",
    customersDeleteConfirm: "هل أنت متأكد من رغبتك في حذف هذا العميل؟",
    customerModalEditTitle: "تعديل بيانات العميل",
    customerModalAddTitle: "إضافة عميل جديد",
    customerModalName: "الاسم",
    customerModalPhone: "رقم الهاتف",
    customerModalEmail: "البريد الإلكتروني",
    customerModalAddress: "العنوان",
    customerPaymentModalTitle: "إضافة دفعة للعميل",
    customerPaymentModalInvalidAmount: "الرجاء إدخال مبلغ صحيح.",
    customerPaymentModalAmount: "المبلغ المدفوع",
    customerPaymentModalNotes: "ملاحظات (اختياري)",
    customerPaymentModalSave: "حفظ الدفعة",
    suppliersTitle: "إدارة الموردين",
    suppliersSearchPlaceholder: "ابحث بالاسم أو الشركة...",
    suppliersAddButton: "إضافة مورد",
    suppliersTableCompany: "الشركة",
    suppliersTableContact: "جهة الاتصال",
    suppliersRegisterPayment: "تسجيل دفعة",
    suppliersDeleteConfirm: "هل أنت متأكد من رغبتك في حذف هذا المورد؟",
    supplierModalEditTitle: "تعديل بيانات المورد",
    supplierModalAddTitle: "إضافة مورد جديد",
    supplierModalContactPerson: "اسم جهة الاتصال",
    supplierModalCompanyName: "اسم الشركة",
    supplierPaymentModalTitle: "تسجيل دفعة للمورد",
    adjustmentsTitle: "تسوية المخزون",
    adjustmentsAddButton: "إضافة تسوية جديدة",
    adjustmentsTableReason: "السبب",
    adjustmentsTableDetails: "التفاصيل",
    adjustmentsTableNoData: "لا توجد تسويات مسجلة.",
    adjustmentReasonDamaged: "تالف",
    adjustmentReasonWaste: "هدر",
    adjustmentReasonCorrection: "تصحيح جرد",
    adjustmentsModalTitle: "تسوية مخزون جديدة",
    adjustmentsModalSearchPlaceholder: "ابحث لإضافة منتج...",
    adjustmentsModalNoProducts: "لم تتم إضافة أي منتجات.",
    adjustmentsModalHelpText: "أدخل كمية موجبة للإضافة للمخزون، وكمية سالبة للخصم منه.",
    adjustmentsModalQuantityError: "يرجى إدخال كميات التغيير للمنتجات.",
    reportsTitle: "التقارير والتحليلات",
    reportsPrintButton: "طباعة التقرير",
    reportsTabProfit: "تقرير الأرباح",
    reportsTabItems: "تحليل الأصناف",
    reportsTabExpiry: "تقرير الصلاحية",
    reportsTabCustomersDebt: "ديون العملاء",
    reportsTabSuppliersDebt: "ديون الموردين",
    reportsDateTo: "إلى",
    reportsPrintDate: "تاريخ الطباعة",
    reportsDateRange: "الفترة من: {0} إلى: {1}",
    reportsTotalRevenue: "إجمالي الإيرادات",
    reportsTotalProfit: "إجمالي الأرباح",
    reportsProfitMargin: "نسبة الربح",
    reportsProfitSummary: "ملخص الأرباح لكل فاتورة",
    reportsRevenue: "الإيراد",
    reportsMostProfitable: "المنتجات الأكثر ربحية",
    reportsSlowMoving: "المنتجات الراكدة (لم تبع)",
    reportsNoSlowMoving: "جميع المنتجات تم بيعها خلال الفترة المحددة.",
    reportsExpiryTitle: "تقرير صلاحية المنتجات",
    reportsExpiryDescription: "يعرض هذا التقرير جميع دفعات المنتجات التي لم تنته صلاحيتها بعد، مرتبة من الأقرب انتهاءً.",
    reportsExpiryQuantity: "الكمية (بالوحدة الأساسية)",
    reportsExpiryDaysLeft: "الأيام المتبقية",
    reportsNoExpiry: "لا توجد منتجات ذات صلاحية قادمة في المخزون.",
    reportsCustomersDebtTitle: "تقرير ديون العملاء (المبالغ المستحقة لك)",
    reportsDebtBalance: "الرصيد المستحق",
    reportsSuppliersDebtTitle: "تقرير ديون الموردين (المبالغ المستحقة عليك)",
    customerProfileTitle: "ملف العميل: {0}",
    customerProfileBackButton: "العودة إلى قائمة العملاء",
    customerProfileData: "بيانات العميل",
    customerProfilePhone: "الهاتف",
    customerProfileEmail: "البريد الإلكتروني",
    customerProfileAddress: "العنوان",
    customerProfileCurrentBalance: "الرصيد الحالي",
    customerProfileDue: "مستحق على العميل",
    customerProfileCredit: "رصيد دائن",
    customerProfileInvoicesTab: "الفواتير ({0})",
    customerProfilePaymentsTab: "الدفعات ({0})",
    supplierProfileTitle: "ملف المورد: {0}",
    supplierProfileBackButton: "العودة إلى قائمة الموردين",
    supplierProfileData: "بيانات المورد",
    supplierProfileContact: "جهة الاتصال",
    supplierProfileDue: "مستحق للمورد",
    supplierProfileDebit: "رصيد مدين",
    supplierProfilePurchasesTab: "المشتريات ({0})",
    supplierProfileStatus: "الحالة",
    purchaseStatusPaid: "مدفوعة",
    purchaseStatusUnpaid: "غير مدفوعة",
    purchaseStatusPartial: "مدفوعة جزئياً",
    saleEditModalTitle: "تعديل / إرجاع الفاتورة: {0}",
    saleEditModalQuantityError: "لا يمكن أن تكون الكمية الجديدة أكبر من الكمية الأصلية ({0}).",
    saleEditModalNewLabel: "الكمية الجديدة لـ {0}",
    saleEditModalOriginalTotal: "الإجمالي الأصلي",
    saleEditModalNewTotal: "الإجمالي الجديد",
    saleEditModalDifference: "الفرق",
    saleEditModalRefund: "سيتم رده للعميل (يخصم من رصيده المستحق)",
    saleEditModalAdditional: "مبلغ إضافي (يضاف إلى رصيده المستحق)",
    saleEditModalSave: "حفظ التعديلات",
    sessionsTitle: "إدارة الجلسات والخزنة",
    sessionsActiveTitle: "جلسة عمل نشطة",
    sessionsStartedAt: "بدأت في: {0} بواسطة {1}",
    sessionsEndButton: "إنهاء الجلسة",
    sessionsOpeningFloat: "الرصيد الافتتاحي",
    sessionsTotalCashSales: "إجمالي المبيعات النقدية",
    sessionsTotalExpenses: "إجمالي المصروفات",
    sessionsExpectedCash: "النقدية المتوقعة",
    sessionsRegisterExpense: "تسجيل المصروفات",
    sessionsExpenseReason: "السبب/ملاحظات",
    sessionsAddExpenseButton: "إضافة مصروف",
    sessionsCurrentExpenses: "مصروفات الجلسة الحالية",
    sessionsNoExpenses: "لا توجد مصروفات مسجلة.",
    sessionsInactiveTitle: "لا توجد جلسة عمل نشطة",
    sessionsInactiveBody: "لبدء تسجيل المبيعات والمصروفات، يجب عليك بدء جلسة عمل جديدة.",
    sessionsStartButton: "بدء جلسة جديدة",
    sessionsHistoryTitle: "سجل الجلسات السابقة",
    sessionsTableStart: "تاريخ البدء",
    sessionsTableEnd: "تاريخ الانتهاء",
    sessionsClosingFloat: "الرصيد الختامي",
    sessionsDifference: "العجز/الزيادة",
    sessionsInvalidAmountError: "الرجاء إدخال مبلغ صحيح.",
    sessionsStartModalTitle: "بدء جلسة جديدة",
    sessionsStartModalLabel: "أدخل الرصيد الافتتاحي في الخزنة",
    sessionsStartModalButton: "بدء الجلسة",
    sessionsEndModalTitle: "إنهاء الجلسة الحالية",
    sessionsEndModalExpected: "النقدية المتوقعة في الخزنة",
    sessionsEndModalActualLabel: "أدخل المبلغ الفعلي بعد العد",
    sessionsEndModalDifference: "الفرق (عجز/زيادة)",
    sessionsEndModalButton: "تأكيد وإنهاء الجلسة",
    sessionsInvalidExpenseError: "يرجى إدخال مبلغ وسبب صحيحين.",
    sessionSummaryTitle: "ملخص الجلسة",
    sessionSummaryUser: "للمستخدم: {0}",
    sessionSummaryPeriod: "من {0} إلى {1}",
    sessionSummaryCardSales: "مبيعات البطاقة",
    sessionSummaryDeferredSales: "المبيعات الآجلة",
    sessionSummarySalesDetails: "تفاصيل المبيعات ({0})",
    sessionSummaryTime: "الوقت",
    sessionSummaryType: "النوع",
    sessionSummaryNoSales: "لا توجد مبيعات",
    sessionSummaryExpensesDetails: "تفاصيل المصروفات ({0})",
    sessionSummaryNoExpenses: "لا توجد مصروفات",
    // FIX: Add translations for Attendance page
    attendanceStatusCheckedIn: 'مسجل حضور',
    hours: 'ساعات',
    minutes: 'دقائق',
    attendanceTableUser: 'المستخدم',
    attendanceTableCheckIn: 'وقت الحضور',
    attendanceTableCheckOut: 'وقت الانصراف',
    attendanceTableDuration: 'المدة',
    attendanceLogTitle: 'سجل الحضور والانصراف',
    attendanceFilterAllUsers: 'كل المستخدمين',
    attendanceNoRecords: 'لا توجد سجلات حضور لعرضها.',
  },
  en: {
    loadingData: "Loading Data",
    pleaseWait: "Please wait a moment",
    customerNotFound: "Customer not found",
    supplierNotFound: "Supplier not found",
    sidebarWelcome: "Welcome, {0}",
    sidebarLogout: "Logout",
    navDashboard: "Dashboard",
    navPOS: "POS",
    navInventory: "Inventory",
    navCategories: "Categories",
    navSales: "Sales",
    navPurchases: "Purchases",
    navSupplierReturns: "Supplier Returns",
    navCustomers: "Customers",
    navSuppliers: "Suppliers",
    navAdjustments: "Stock Adjustments",
    navReports: "Reports",
    navSessions: "Session Management",
    navSettings: "Settings",
    // Settings Page
    settingsTitle: 'Settings',
    languageSettings: 'Language Settings',
    appLanguage: 'Application Language',
    languageArabic: 'العربية',
    languageEnglish: 'English',
    currencySettings: 'Currency Settings',
    appCurrency: 'Application Currency',
    saveCurrency: 'Save Currency',
    currencyEGP: 'Egyptian Pound (EGP)',
    currencyUSD: 'US Dollar (USD)',
    currencyEUR: 'Euro (EUR)',
    currencySAR: 'Saudi Riyal (SAR)',
    generalSettings: 'General Settings',
    taxRate: 'Tax Rate',
    showTaxInReceipt: 'Show Tax in Receipt',
    saveTaxRate: 'Save Tax Rate',
    savedSuccessfully: 'Saved successfully!',
    storeInfo: 'Store Info (for receipts)',
    storeName: 'Store Name',
    storeAddress: 'Address',
    storePhone: 'Phone',
    storeLogo: 'Store Logo',
    browseFiles: 'Browse Files',
    saveStoreInfo: 'Save Store Info',
    userManagement: 'User Management',
    addUser: 'Add User',
    username: 'Username',
    role: 'Role',
    actions: 'Actions',
    roleAdmin: 'Admin',
    roleCashier: 'Cashier',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: "Confirm Deletion",
    deleteUserConfirmation: 'Are you sure you want to delete the user "{0}"? This action cannot be undone.',
    cancel: "Cancel",
    confirm: "Confirm",
    editUser: "Edit User",
    addNewUser: "Add New User",
    usernameRequired: "Username is required.",
    passwordRequired: "Password is required for a new user.",
    password: "Password",
    usernameCannotBeChanged: "Username cannot be changed.",
    leaveBlankToKeep: "Leave blank to keep unchanged",
    save: "Save",
    networkSyncSettings: "Network Sync",
    networkSyncDescription: "To enable real-time sync between devices, run the sync server on a main computer and enter its address here on all other devices.",
    serverUrlLabel: "Sync Server URL",
    serverUrlPlaceholder: "e.g., ws://192.168.1.5:8080",
    connectionStatusLabel: "Connection Status",
    statusConnected: "Connected",
    statusConnecting: "Connecting...",
    statusDisconnected: "Disconnected",
    saveServerUrlButton: "Save & Connect",
    dataManagement: "Data Management",
    dataManagementDescription: "Export all your data into a single file for backup, or import a backup file to restore data. Warning: Importing will delete all current data.",
    exportData: "Export Data",
    importData: "Import Data",
    importConfirmMessage: "Warning! Importing data will permanently delete all current data and replace it with the data from the backup file. Are you sure you want to continue?",
    restoreConfirmMessage: "Are you sure you want to restore the backup from {0}? All current data will be deleted.",
    autoBackupTitle: "Automatic Daily Backups",
    autoBackupTimeSetting: "Automatic Backup Time",
    autoBackupTimeDescription: "Select the time for the daily backup. It will run when the app is opened after this time.",
    saveBackupTime: "Save Time",
    autoBackupDescription: "The system automatically creates a daily backup and keeps the last 7 copies. You can restore or download any of them.",
    noAutoBackups: "No automatic backups available.",
    backupDate: "Backup from: {0}",
    restore: "Restore",
    download: "Download",
    confirmActionTitle: "Confirm Action",
    importSuccess: "Data imported successfully! The application will now reload.",
    importFailed: "Import failed: {0}",
    exportFailed: "Export failed: {0}",
    backupNotFound: "Backup not found.",
    settingsAutoFileBackup: "Automatic File Backup",
    settingsAutoFileBackupDesc: "Select a folder on your computer to automatically save daily backups. The browser will ask for permission once.",
    settingsChooseFolder: "Choose Folder",
    settingsSelectedFolder: "Selected Folder",
    settingsClearSelection: "Clear",
    settingsFolderSetSuccess: "Backup folder set successfully!",
    settingsFolderCleared: "Backup folder selection cleared.",
    settingsFileSystemNotSupported: "Feature Not Supported",
    settingsFileSystemNotSupportedDesc: "This feature is only available in modern desktop browsers like Chrome and Edge.",
    settingsFileSystemInsecure: "Secure Context Required",
    settingsFileSystemInsecureDesc: "For security, this feature only works when the app is accessed via `localhost` or an `https` connection. Accessing via a local network IP address (e.g., http://192.168.x.x) is not supported.",
    autoBackupSavedToFile: "Automatic backup also saved to your chosen folder.",
    autoBackupFileSaveError: "Could not save backup to the selected folder. Please check permissions.",
    // Login Page
    loginWelcome: "Welcome back! Please sign in.",
    loginButton: "Sign In",
    loginError: "Incorrect username or password.",
    // Dashboard
    dashboardTitle: "Main Dashboard",
    totalSales: "Total Sales",
    totalTransactions: "Transactions",
    totalProducts: "Total Products",
    lowStockProducts: "Low Stock Products",
    weeklySales: "This Week's Sales",
    noSalesThisWeek: "No sales recorded this week.",
    slowMovingProducts: "Slow-Moving Products (not sold in 30 days)",
    stockLabel: "Stock",
    noSlowMovingProducts: "No slow-moving products currently.",
    latestSales: "Latest Sales",
    invoiceNumber: "Invoice #",
    date: "Date",
    paymentMethod: "Payment Method",
    total: "Total",
    dismissAlert: "Dismiss alert",
    // Payment Methods
    paymentMethodCash: 'Cash',
    paymentMethodCard: 'Card',
    paymentMethodDeferred: 'Deferred',
    paymentMethodMultiple: 'Multiple',
    paymentMethodUnspecified: 'Unspecified',
    // Notifications
    notifLowStock: 'Product "{0}" is running low. Remaining quantity: {1}',
    notifExpiry: 'Batches of product "{0}" are nearing their expiration date.',
    // POS Page
    scanBarcodePlaceholder: "Scan or enter barcode...",
    searchProductsPlaceholder: "Search for products...",
    categories: "Categories",
    allCategories: "All",
    home: "Home",
    noItemsToDisplay: "No items to display.",
    posBill: "Bill",
    parkedSalesTitle: "Parked Sales",
    posEmptyCart: "The cart is empty",
    subtotal: "Subtotal",
    discount: "Discount",
    tax: "Tax",
    customer: "Customer",
    customerNamePlaceholder: "Enter customer name...",
    newCustomerWillBeCreated: "A new customer will be created with this name.",
    pay: "Pay",
    deferredSale: "Deferred Sale",
    parkSale: "Park Sale",
    sessionClosedTitle: "Session Closed",
    sessionClosedBody: "You must start a new work session from the Session Management page to be able to record sales.",
    cashCustomer: "Cash Customer",
    productNotFound: "Product not found",
    productNotFoundInStock: "Product '{0}' could not be found in stock.",
    insufficientStockError: "Failed to complete sale for product \"{0}\": Requested quantity ({1}) is greater than available quantity ({2}).",
    deferredSaleCashCustomerError: "Deferred sale is not allowed for 'Cash Customer'. Please enter a customer name.",
    deferredSaleNoCreateError: "Cannot complete a deferred sale without registering the customer.",
    saleCompletionError: "An error occurred while completing the sale. Please try again.",
    saleFailedWithReason: "Sale failed: {0}",
     // POS Modals
    weightEntryTitle: "Enter Weight for: {0}",
    pricePerUnit: "Price per {0}: {1}",
    weightPlaceholder: "Weight in ({0})",
    calculatedPrice: "Calculated Price",
    add: "Add",
    unregisteredCustomerTitle: "Unregistered Customer",
    unregisteredCustomerBody: 'The customer "{0}" does not exist. Would you like to add them to the customer list?',
    unregisteredCustomerDeferredNote: "Note: A deferred sale cannot be completed without registering the customer.",
    cancelSale: "Cancel Sale",
    continueSaleOnly: "No, Continue Sale Only",
    addAndContinue: "Yes, Add and Continue",
    selectUnitFor: "Select a unit for: {0}",
    parkedSaleOnDate: "Sale parked on: {0}",
    parkedSaleDetails: "Items: {0}, Total: {1}",
    retrieve: "Retrieve",
    noParkedSales: "There are no parked sales.",
    parkedSaleNote: 'Sale for {0}',
     // Payment Modal
    cashPaymentTitle: "Cash Payment",
    totalAmountDue: "Total Amount Due",
    amountReceivedFromCustomer: "Amount Received from Customer",
    exactAmount: "Exact Amount",
    changeDueToCustomer: "Change Due to Customer",
    completeSale: "Complete Sale",
    // hooks/usePosState.ts
    categoryInUseError: "Cannot delete category because it is in use by some products.",
    saleUpdatedSuccess: "Sale updated successfully.",
    addPurchaseError: "Failed to add purchase.",
    purchaseNotFound: "Purchase not found.",
    deletePurchaseError: "Failed to delete purchase.",
    addSupplierReturnError: "Failed to add supplier return.",
    supplierReturnNotFound: "Supplier return not found.",
    deleteSupplierReturnError: "Failed to delete supplier return.",
    cannotDeleteCurrentUser: "You cannot delete the current user.",
    noCurrentUser: "No current user.",
    sessionAlreadyActive: "A work session is already active.",
    mustStartSessionFirst: "You must start a session first to add an expense.",
    noActiveSessionToEnd: "No active session to end.",
    // pages/Sales.tsx
    itemCount: "Item Count",
    cost: "Cost",
    profit: "Profit",
    salesLogTitle: "Sales Log",
    searchByInvoiceNumber: "Search by invoice number...",
    searchByCustomerName: "Search by customer name...",
    exporting: "Exporting...",
    exportSelectedToWord: "Export Selected to Word",
    exportToExcel: "Export to Excel",
    selectAll: "Select All",
    selectInvoice: "Select invoice {0}",
    returnEdit: "Return / Edit",
    exportAsImage: "Export as Image",
    print: "Print",
    // components/Receipt.tsx
    allowPopupsForPrinting: "Please allow popups for printing.",
    storeLogoAlt: "Store Logo",
    phoneLabel: "Phone",
    item: "Item",
    quantity: "Qty",
    price: "Price",
    paidWith: "Paid with {0}",
    newBalance: "New Balance",
    thankYouMessage: "Thank you for your visit!",
    close: "Close",
    // New Translations
    inventoryTitle: "Inventory Management",
    inventorySearchPlaceholder: "Search by name or SKU...",
    inventoryFilterAllCategories: "All Categories",
    inventoryFilterAllStock: "All Stock Statuses",
    inventoryFilterInStock: "In Stock",
    inventoryFilterLowStock: "Low Stock",
    inventoryFilterOutOfStock: "Out of Stock",
    inventoryAddNewProduct: "Add New Product",
    inventoryTableProduct: "Product",
    inventoryTableSku: "SKU",
    inventoryTableCategory: "Category",
    inventoryTablePrice: "Price (Largest Unit)",
    inventoryTablePriceUnit: "Price Unit",
    inventoryTableStock: "Stock",
    inventoryTableStockUnit: "Stock Unit",
    inventoryPrintBarcode: "Print Barcode",
    inventoryDeleteConfirmMessage: "Are you sure you want to delete this item?",
    inventoryStatusExpiresSoon: "Expires Soon",
    inventoryStatusLowStock: "Low Stock",
    inventoryStatusOutOfStock: "Out of Stock",
    barcodeLabelTitle: "Barcode Label",
    productModalEditTitle: "Edit Product",
    productModalAddTitle: "Add New Product",
    productModalProductName: "Product Name",
    productModalProductNamePlaceholder: "e.g., Espresso Coffee",
    productModalSku: "SKU (Barcode)",
    productModalSkuPlaceholder: "Scan or enter barcode manually",
    productModalCategory: "Category",
    productModalCategorySelect: "-- Select a category --",
    productModalSellingMethod: "Selling Method",
    productModalSellingMethodUnit: "By Unit (piece, box..)",
    productModalSellingMethodWeight: "By Weight (kg, gram..)",
    productModalUnitsAndPrices: "Units and Prices",
    productModalUnitHelpTextUnit: "Start by entering the largest unit (e.g., carton). Then add smaller units within it.",
    productModalUnitHelpTextWeight: "Enter the base unit of weight (e.g., Kilogram) and its selling/cost price.",
    productModalBaseUnitLargest: "Base Unit (Largest)",
    productModalBaseUnitWeight: "Base Unit of Weight",
    productModalOfNextUnit: "of the next unit",
    productModalUnitNameLabel: "Unit Name",
    productModalUnitNamePlaceholderUnit: "Carton, Box..",
    productModalUnitNamePlaceholderWeight: "Kilogram, Gram..",
    productModalSellingPrice: "Selling Price ({0})",
    productModalCostPrice: "Cost Price ({0})",
    productModalUnit: "Unit",
    productModalAddSmallerUnit: "+ Add smaller unit",
    productModalInitialStock: "Initial Stock Quantity",
    productModalCannotEditStock: "Stock cannot be edited here. Use Purchases or Adjustments.",
    productModalStockHelpText: "The quantity will be stored in the smallest defined unit.",
    productModalExpiryDate: "Expiry Date",
    productModalImage: "Product Image (optional)",
    productModalNoImage: "No Image",
    productModalDescription: "Product Description",
    productModalDescriptionPlaceholder: "A short and attractive description...",
    productModalCompleteUnitInfo: "Unit information must be completed for all units.",
    productModalStockUnitError: "Error determining stock unit.",
    categoriesTitle: "Category Management",
    categorySearchPlaceholder: "Search for a category...",
    categoryAddMain: "Add Main Category",
    categorySearchResults: "Search results for \"{0}\"",
    categoryTreeTitle: "Category Tree",
    categoryNoResults: "No categories match your search.",
    categoryProductCount: "Products: {0}",
    categoryAddSub: "Add Sub",
    categoryDeleteConfirm: "Are you sure you want to delete this category and all its subcategories?",
    categoryModalEditTitle: "Edit Category",
    categoryModalAddSubTitle: "Add Subcategory to {0}",
    categoryModalAddMainTitle: "Add Main Category",
    categoryModalNamePlaceholder: "Category Name",
    categoryModalImageLabel: "Category Image (optional)",
    categoryModalImagePlaceholder: "Image",
    categoryModalImagePreviewAlt: "Preview",
    categoryModalChangeImage: "Change Image",
    categoryModalParentOptionMain: "-- Main Category --",
    purchasesTitle: "Purchase Management",
    purchasesAddButton: "Add Purchase Invoice",
    purchasesTableInvoice: "Invoice #",
    purchasesTableSupplier: "Supplier",
    purchasesTablePaid: "Paid",
    purchasesTableView: "View",
    purchasesDeleteConfirm: "Are you sure you want to delete this invoice? Stock and supplier balance changes will be reverted.",
    purchaseDetailsTitle: "Purchase Invoice Details",
    purchaseDetailsRemaining: "Remaining",
    notes: "Notes",
    notesOptional: "Notes (optional)",
    purchaseModalTitle: "Add New Purchase Invoice",
    purchaseModalSelectSupplier: "-- Select Supplier --",
    purchaseModalReference: "Reference Number",
    purchaseModalReferenceOptional: "Reference Number (optional)",
    purchaseModalItems: "Items",
    purchaseModalSearchProduct: "Search for a product...",
    purchaseModalSelectUnit: "-- Select Unit --",
    purchaseModalExpiresOn: "Expires on: {0}",
    purchaseModalValidationError: "Please ensure a product and unit are selected, and that quantity and cost price are valid.",
    purchaseModalNoItems: "No items have been added yet.",
    purchaseModalAmountPaid: "Amount Paid",
    purchaseModalNotesPlaceholder: "Any additional details...",
    purchaseModalSaveButton: "Save Purchase Invoice",
    purchaseModalSupplierItemError: "Please select a supplier and add at least one item.",
    purchaseModalInvalidAmountError: "The paid amount is invalid.",
    returnsTitle: "Supplier Returns",
    returnsAddButton: "Add New Return",
    returnsTableReturnNo: "Return #",
    returnsDeleteConfirm: "Are you sure? Stock and supplier balance changes will be reverted.",
    returnDetailsTitle: "Supplier Return Details",
    returnDetailsTotal: "Total Return Value",
    returnModalTitle: "Add New Supplier Return",
    returnModalReturnedItems: "Returned Items",
    purchaseModalSelectUnitFirst: "Select Product First",
    returnModalTotal: "Total Return Value",
    returnModalSaveButton: "Save Return",
    customersTitle: "Customer Management",
    customersSearchPlaceholder: "Search by name or phone...",
    customersAddButton: "Add Customer",
    customersTableName: "Name",
    customersTablePhone: "Phone",
    customersTableBalance: "Balance",
    customersAddPayment: "Add Payment",
    customersDeleteConfirm: "Are you sure you want to delete this customer?",
    customerModalEditTitle: "Edit Customer",
    customerModalAddTitle: "Add New Customer",
    customerModalName: "Name",
    customerModalPhone: "Phone Number",
    customerModalEmail: "Email",
    customerModalAddress: "Address",
    customerPaymentModalTitle: "Add Customer Payment",
    customerPaymentModalInvalidAmount: "Please enter a valid amount.",
    customerPaymentModalAmount: "Amount Paid",
    customerPaymentModalNotes: "Notes (optional)",
    customerPaymentModalSave: "Save Payment",
    suppliersTitle: "Supplier Management",
    suppliersSearchPlaceholder: "Search by name or company...",
    suppliersAddButton: "Add Supplier",
    suppliersTableCompany: "Company",
    suppliersTableContact: "Contact Person",
    suppliersRegisterPayment: "Register Payment",
    suppliersDeleteConfirm: "Are you sure you want to delete this supplier?",
    supplierModalEditTitle: "Edit Supplier",
    supplierModalAddTitle: "Add New Supplier",
    supplierModalContactPerson: "Contact Person Name",
    supplierModalCompanyName: "Company Name",
    supplierPaymentModalTitle: "Register Supplier Payment",
    adjustmentsTitle: "Stock Adjustments",
    adjustmentsAddButton: "Add New Adjustment",
    adjustmentsTableReason: "Reason",
    adjustmentsTableDetails: "Details",
    adjustmentsTableNoData: "No adjustments recorded.",
    adjustmentReasonDamaged: "Damaged",
    adjustmentReasonWaste: "Waste",
    adjustmentReasonCorrection: "Inventory Correction",
    adjustmentsModalTitle: "New Stock Adjustment",
    adjustmentsModalSearchPlaceholder: "Search to add a product...",
    adjustmentsModalNoProducts: "No products have been added.",
    adjustmentsModalHelpText: "Enter a positive quantity to add to stock, and a negative quantity to deduct.",
    adjustmentsModalQuantityError: "Please enter quantity changes for the products.",
    reportsTitle: "Reports & Analytics",
    reportsPrintButton: "Print Report",
    reportsTabProfit: "Profit Report",
    reportsTabItems: "Item Analysis",
    reportsTabExpiry: "Expiry Report",
    reportsTabCustomersDebt: "Customer Debts",
    reportsTabSuppliersDebt: "Supplier Debts",
    reportsDateTo: "to",
    reportsPrintDate: "Print Date",
    reportsDateRange: "Period from: {0} to: {1}",
    reportsTotalRevenue: "Total Revenue",
    reportsTotalProfit: "Total Profit",
    reportsProfitMargin: "Profit Margin",
    reportsProfitSummary: "Profit Summary per Invoice",
    reportsRevenue: "Revenue",
    reportsMostProfitable: "Most Profitable Products",
    reportsSlowMoving: "Slow-Moving Products (not sold)",
    reportsNoSlowMoving: "All products have been sold during the selected period.",
    reportsExpiryTitle: "Product Expiry Report",
    reportsExpiryDescription: "This report shows all unexpired product batches, sorted by the nearest expiry date.",
    reportsExpiryQuantity: "Quantity (Base Unit)",
    reportsExpiryDaysLeft: "Days Remaining",
    reportsNoExpiry: "No products with upcoming expiry dates in stock.",
    reportsCustomersDebtTitle: "Customer Debts Report (Amounts owed to you)",
    reportsDebtBalance: "Balance Due",
    reportsSuppliersDebtTitle: "Supplier Debts Report (Amounts you owe)",
    customerProfileTitle: "Customer Profile: {0}",
    customerProfileBackButton: "Back to Customer List",
    customerProfileData: "Customer Data",
    customerProfilePhone: "Phone",
    customerProfileEmail: "Email",
    customerProfileAddress: "Address",
    customerProfileCurrentBalance: "Current Balance",
    customerProfileDue: "Due from customer",
    customerProfileCredit: "Credit balance",
    customerProfileInvoicesTab: "Invoices ({0})",
    customerProfilePaymentsTab: "Payments ({0})",
    supplierProfileTitle: "Supplier Profile: {0}",
    supplierProfileBackButton: "Back to Supplier List",
    supplierProfileData: "Supplier Data",
    supplierProfileContact: "Contact Person",
    supplierProfileDue: "Due to supplier",
    supplierProfileDebit: "Debit balance",
    supplierProfilePurchasesTab: "Purchases ({0})",
    supplierProfileStatus: "Status",
    purchaseStatusPaid: "Paid",
    purchaseStatusUnpaid: "Unpaid",
    purchaseStatusPartial: "Partially Paid",
    saleEditModalTitle: "Edit / Return Invoice: {0}",
    saleEditModalQuantityError: "New quantity cannot be greater than the original quantity ({0}).",
    saleEditModalNewLabel: "New quantity for {0}",
    saleEditModalOriginalTotal: "Original Total",
    saleEditModalNewTotal: "New Total",
    saleEditModalDifference: "Difference",
    saleEditModalRefund: "To be refunded to customer (deducted from their balance)",
    saleEditModalAdditional: "Additional amount (added to their balance)",
    saleEditModalSave: "Save Changes",
    sessionsTitle: "Session & Cash Drawer Management",
    sessionsActiveTitle: "Active Work Session",
    sessionsStartedAt: "Started at: {0} by {1}",
    sessionsEndButton: "End Session",
    sessionsOpeningFloat: "Opening Float",
    sessionsTotalCashSales: "Total Cash Sales",
    sessionsTotalExpenses: "Total Expenses",
    sessionsExpectedCash: "Expected Cash",
    sessionsRegisterExpense: "Register Expense",
    sessionsExpenseReason: "Reason / Notes",
    sessionsAddExpenseButton: "Add Expense",
    sessionsCurrentExpenses: "Current Session Expenses",
    sessionsNoExpenses: "No expenses recorded.",
    sessionsInactiveTitle: "No Active Work Session",
    sessionsInactiveBody: "To start recording sales and expenses, you must start a new work session.",
    sessionsStartButton: "Start New Session",
    sessionsHistoryTitle: "Previous Sessions History",
    sessionsTableStart: "Start Time",
    sessionsTableEnd: "End Time",
    sessionsClosingFloat: "Closing Float",
    sessionsDifference: "Difference",
    sessionsInvalidAmountError: "Please enter a valid amount.",
    sessionsStartModalTitle: "Start New Session",
    sessionsStartModalLabel: "Enter opening float in cash drawer",
    sessionsStartModalButton: "Start Session",
    sessionsEndModalTitle: "End Current Session",
    sessionsEndModalExpected: "Expected cash in drawer",
    sessionsEndModalActualLabel: "Enter actual amount after counting",
    sessionsEndModalDifference: "Difference (Shortage/Overage)",
    sessionsEndModalButton: "Confirm & End Session",
    sessionsInvalidExpenseError: "Please enter a valid amount and reason.",
    sessionSummaryTitle: "Session Summary",
    sessionSummaryUser: "For user: {0}",
    sessionSummaryPeriod: "From {0} to {1}",
    sessionSummaryCardSales: "Card Sales",
    sessionSummaryDeferredSales: "Deferred Sales",
    sessionSummarySalesDetails: "Sales Details ({0})",
    sessionSummaryTime: "Time",
    sessionSummaryType: "Type",
    sessionSummaryNoSales: "No sales",
    sessionSummaryExpensesDetails: "Expenses Details ({0})",
    sessionSummaryNoExpenses: "No expenses",
    // FIX: Add translations for Attendance page
    attendanceStatusCheckedIn: 'Checked In',
    hours: 'hours',
    minutes: 'minutes',
    attendanceTableUser: 'User',
    attendanceTableCheckIn: 'Check-In Time',
    attendanceTableCheckOut: 'Check-Out Time',
    attendanceTableDuration: 'Duration',
    attendanceLogTitle: 'Attendance Log',
    attendanceFilterAllUsers: 'All Users',
    attendanceNoRecords: 'No attendance records to display.',
  }
};

export type TranslationKey = keyof typeof translations.ar;
type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  currency: string;
  setCurrency: (currency: string) => void;
  t: (key: TranslationKey, ...args: any[]) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('ar');
  const [currency, setCurrencyState] = useState<string>('EGP');

  useEffect(() => {
    const loadSettings = async () => {
      try {
        const langSetting = await db.settings.get('language');
        if (langSetting && (langSetting.value === 'ar' || langSetting.value === 'en')) {
          const lang = langSetting.value as Language;
          setLanguageState(lang);
          document.documentElement.lang = lang;
          document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        } else {
            document.documentElement.lang = 'ar';
            document.documentElement.dir = 'rtl';
            await db.settings.put({ key: 'language', value: 'ar' });
        }

        const currencySetting = await db.settings.get('currency');
        if (currencySetting && typeof currencySetting.value === 'string') {
          setCurrencyState(currencySetting.value);
        } else {
            await db.settings.put({ key: 'currency', value: 'EGP' });
        }

      } catch (error) {
          console.error("Failed to load settings:", error);
          document.documentElement.lang = 'ar';
          document.documentElement.dir = 'rtl';
      }
    };
    db.on('ready', loadSettings);

    return () => {
        db.on('ready').unsubscribe(loadSettings);
    }
  }, []);

  const setLanguage = useCallback(async (lang: Language) => {
    await db.settings.put({ key: 'language', value: lang });
    setLanguageState(lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, []);
  
  const setCurrency = useCallback(async (curr: string) => {
    await db.settings.put({ key: 'currency', value: curr });
    setCurrencyState(curr);
  }, []);

  const t = (key: TranslationKey, ...args: any[]): string => {
    let text = (translations[language] as any)[key] || (translations['en'] as any)[key] || key;
    if (args.length > 0) {
      args.forEach((arg, index) => {
        text = text.replace(`{${index}}`, String(arg));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, currency, setCurrency, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};